# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Enables Late Deploy (Post Server Start)

[tags]
deploy

[depends]
server

[files]
webapps-late/
# maven://org.eclipse.jetty/jetty-late-deploy/${jetty.version}|lib/jetty-late-deploy-${jetty.version}.jar

[lib]
lib/jetty-late-deploy-1.0-SNAPSHOT.jar

[xml]
etc/jetty-late-deploy.xml